#!/usr/bin/env bash
#
# Build the Paperless demo estate, from nothing, and emit the two artifacts the
# published images are baked from:
#
#   db/demo.sql.gz        the database half of the estate
#   estate/media.tar.gz   the files that database points at
#
# Usage, from the host directory (paperless/):
#
#   FRISIAN_MCP_LOCAL_WHEEL=frisian_mcp-1.1.0-py3-none-any.whl ./seed/seed.sh
#   FRISIAN_MCP_SPEC='frisian-mcp[usage]==1.1.0'               ./seed/seed.sh
#
# Exactly one of those two. The Dockerfile refuses a build with neither or both.
#
# ─────────────────────────────────────────────────────────────────────────────
# WHY THIS SEEDS IN THE OPEN, UNLIKE THE NAUTOBOT HOST
# ─────────────────────────────────────────────────────────────────────────────
#
# The Nautobot host's golden dump is produced OUTSIDE this repository and
# fetched as an artifact, because it descends from a live, internet-facing
# instance: seeding it here would put a credential-reset script in the position
# of being the only control between an ordinary bug and working credentials on
# the open internet.
#
# This estate has no such ancestry. Every byte of it is generated by
# seed/corpus.py and seed/build_estate.py, both committed to this repository,
# from fiction. There is no inherited database, no inherited credential, and
# nothing to reset — so the artifact this script produces is safe by
# construction rather than safe by scrubbing.
#
# That buys a property the Nautobot host does not have: anyone can rebuild the
# entire demo from a clone, and CI can run this script directly instead of
# depending on an artifact hosted somewhere else. Do not "align" it with the
# Nautobot pipeline by moving the seed out of the repo. The asymmetry is the
# consequence of a real difference between the two estates.
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HOST_DIR="$(cd "$HERE/.." && pwd)"
cd "$HOST_DIR"

COMPOSE=(docker compose -f docker-compose.yml -f seed/docker-compose.seed.yml)

# Pinned. reportlab's output is byte-stable within a version and not guaranteed
# to be across versions, and this pipeline's reproducibility rests on the
# corpus PDFs having the same checksums every run. Bump it deliberately, and
# expect every document's checksum to change when you do.
REPORTLAB="reportlab==4.2.5"

CORPUS_DIR="$HOST_DIR/seed/out"

note() { printf '\n\033[1m── %s\033[0m\n' "$*"; }

# ── Guard: one lane, and it must be stated ──────────────────────────────────
if [ -n "${FRISIAN_MCP_SPEC:-}" ] && [ -n "${FRISIAN_MCP_LOCAL_WHEEL:-}" ]; then
  echo "ERROR: FRISIAN_MCP_SPEC and FRISIAN_MCP_LOCAL_WHEEL are both set. Pick one lane." >&2
  exit 1
fi
if [ -z "${FRISIAN_MCP_SPEC:-}" ] && [ -z "${FRISIAN_MCP_LOCAL_WHEEL:-}" ]; then
  echo "ERROR: no frisian-mcp source selected, and there is no default." >&2
  echo "  PyPI lane:  FRISIAN_MCP_SPEC='frisian-mcp[usage]==1.1.0'" >&2
  echo "  Local lane: FRISIAN_MCP_LOCAL_WHEEL=<file in paperless/wheels/>" >&2
  exit 1
fi
export FRISIAN_MCP_SPEC="${FRISIAN_MCP_SPEC:-}"
export FRISIAN_MCP_LOCAL_WHEEL="${FRISIAN_MCP_LOCAL_WHEEL:-}"

cleanup() {
  note "tearing the seed stack down"
  "${COMPOSE[@]}" down -v --remove-orphans >/dev/null 2>&1 || true
}
trap cleanup EXIT

# ── 0. Start from nothing ───────────────────────────────────────────────────
#
# The previous run's artifacts are removed FIRST, and specifically before the
# image build. estate/ is COPYed into the application image, so a stale
# media.tar.gz left in place would be baked into the seed image — and the
# restore hook would then unpack an old estate over the media directory this
# run is about to fill. The result is a corpus consumed twice and a dump that
# does not match anything.
note "clearing previous artifacts"
rm -rf "$CORPUS_DIR"
rm -f "$HOST_DIR/db/demo.sql.gz" "$HOST_DIR/estate/media.tar.gz"
"${COMPOSE[@]}" down -v --remove-orphans >/dev/null 2>&1 || true

# ── 1. Generate the corpus ──────────────────────────────────────────────────
#
# In a throwaway container, so the estate does not depend on what happens to be
# installed on the machine running this. Same container, same output, laptop or
# CI.
note "generating the document corpus"
mkdir -p "$CORPUS_DIR"
docker run --rm \
  -v "$HOST_DIR/seed:/seed:ro" \
  -v "$CORPUS_DIR:/out" \
  docker.io/library/python:3.12-slim \
  sh -c "pip install --quiet --no-cache-dir ${REPORTLAB} && python /seed/corpus.py /out"

EXPECTED=$(find "$CORPUS_DIR" -maxdepth 1 -name '*.pdf' | wc -l | tr -d ' ')
[ "$EXPECTED" -gt 0 ] || { echo "ERROR: the corpus generator produced no PDFs." >&2; exit 1; }
echo "  ${EXPECTED} documents"

# ── 2. Boot a stack with an EMPTY database ──────────────────────────────────
note "booting the seed stack"
"${COMPOSE[@]}" up -d --build --wait --wait-timeout 900

# ── 3. Provision identities, including the build-only one ───────────────────
#
# The builder is scoped rather than superuser on purpose: a superuser cannot be
# refused, so it would silently paper over a missing capability that this run
# exists to exercise.
note "provisioning identities (with the build-only identity)"
"${COMPOSE[@]}" exec -T --user paperless \
  -e DEMO_PROVISION_BUILDER=1 \
  paperless python3 manage.py shell < db/provision_identities.py

# ── 4. Consume the corpus ───────────────────────────────────────────────────
#
# Copied out of the read-only mount into the watched folder, so a bug here
# cannot eat the source corpus.
note "consuming ${EXPECTED} documents"
"${COMPOSE[@]}" exec -T paperless bash -c '
  set -e
  cp /usr/src/paperless/demo-seed/*.pdf /usr/src/paperless/consume/
  chown paperless:paperless /usr/src/paperless/consume/*.pdf
'
# ⚠️ DO NOT ADD `document_consumer --oneshot` HERE. It was here, as "belt and
# braces in case inotify does not fire on a bind mount", and it is what put 13
# FAILURE and 10 PENDING tasks into the published demo estate.
#
# The running consumer already watches this directory. `--oneshot` rescans it
# and queues everything still present, so every file gets queued TWICE: the
# first consume moves the file out, the second finds nothing and fails with
# "Cannot consume ...: File not found". The failures then ride into demo.sql.gz
# and every user of the demo sees a task list full of red.
#
# The watcher is not a guess — it demonstrably consumes all of them, and the
# poll below is the safety net if it ever stops doing so. A timeout that says
# "stalled at 19/24" is a better failure than a silent double-queue.

# Poll rather than sleep. Consumption is asynchronous, and a fixed sleep is
# either too short (a short estate, silently) or too long (every build).
note "waiting for consumption to finish"
deadline=$(( SECONDS + 1200 ))
while :; do
  # Counted with psql against the database, NOT with `manage.py shell -c`.
  #
  # Measured: django-extensions is installed in the Paperless image, so it
  # overrides `shell` and prints "46 objects imported automatically" BEFORE the
  # value. Scraping digits out of that gave `46` concatenated with the real
  # count — "4623" for a count of 23, which sails past a `-ge 24` test on the
  # first poll. The loop then exited with two thirds of the corpus still in the
  # queue, and the failure surfaced two steps later as eighteen unconsumed
  # files.
  #
  # psql -qtAX emits the value and nothing else, from a process with no Django
  # startup to narrate.
  count=$("${COMPOSE[@]}" exec -T db \
      psql -qtAX -U "${POSTGRES_USER:-paperless}" -d "${POSTGRES_DB:-paperless}" \
      -c 'SELECT count(*) FROM documents_document;' 2>/dev/null | tr -dc '0-9')
  count="${count:-0}"
  printf '\r  %s/%s consumed' "$count" "$EXPECTED"
  [ "$count" -ge "$EXPECTED" ] && { printf '\n'; break; }
  if [ "$SECONDS" -ge "$deadline" ]; then
    printf '\n'
    echo "ERROR: consumption stalled at ${count}/${EXPECTED} after 20 minutes." >&2
    echo "Consumer log:" >&2
    "${COMPOSE[@]}" logs --no-color --tail 100 paperless >&2 || true
    exit 1
  fi
  sleep 5
done

# ── 5. File everything according to the manifest ────────────────────────────
note "applying the estate metadata"
"${COMPOSE[@]}" exec -T --user paperless paperless \
  python3 manage.py shell < seed/build_estate.py

# ── 6. Remove the build-only identity ───────────────────────────────────────
#
# Re-running the provisioner WITHOUT the flag is what deletes it — the script
# is declarative, so "absent" is a state it enforces rather than something this
# script has to know how to undo.
note "removing the build-only identity"
"${COMPOSE[@]}" exec -T --user paperless paperless \
  python3 manage.py shell < db/provision_identities.py

# ── 7. Leave no residue in the watched folder ───────────────────────────────
#
# The consume directory is a tmpfs and would not survive anyway, but the media
# tarball is taken from a live container and a stray file there would ship.
"${COMPOSE[@]}" exec -T paperless bash -c 'rm -f /usr/src/paperless/consume/*.pdf'

# ── 8. Harvest both halves of the artifact ──────────────────────────────────
#
# Dumped from INSIDE the db container, so pg_dump and the server are the same
# version by construction. A newer client emits GUCs an older server rejects in
# the dump preamble, and the postgres entrypoint restores with ON_ERROR_STOP —
# so that mismatch is a fatal, partial restore rather than a warning.
note "dumping the database"
"${COMPOSE[@]}" exec -T db \
  pg_dump -U "${POSTGRES_USER:-paperless}" -d "${POSTGRES_DB:-paperless}" \
  | gzip -9 > "$HOST_DIR/db/demo.sql.gz"
gzip -t "$HOST_DIR/db/demo.sql.gz"

note "archiving the media tree"
"${COMPOSE[@]}" exec -T paperless \
  tar -czf - -C /usr/src/paperless/media . > "$HOST_DIR/estate/media.tar.gz"
gzip -t "$HOST_DIR/estate/media.tar.gz"

# ── 9. Say what was produced ────────────────────────────────────────────────
sql_size=$(wc -c < "$HOST_DIR/db/demo.sql.gz" | tr -d ' ')
media_size=$(wc -c < "$HOST_DIR/estate/media.tar.gz" | tr -d ' ')

cat <<EOS

── seeded ───────────────────────────────────────────
  db/demo.sql.gz         ${sql_size} bytes
  estate/media.tar.gz    ${media_size} bytes
  documents              ${EXPECTED}

These two are HALVES OF ONE ARTIFACT. The dump references files that live in
the tarball. Baking one without the other produces a demo where every document
listing works and every download 404s.

Next:
  docker compose -f docker-compose.yml -f docker-compose.build.yml up --build
EOS
